# Решение заданий к уроку 5

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$



In [8]:
import numpy as np
np.set_printoptions(precision=7, suppress=True)

In [9]:
A = np.array([[1, 2,0],
              [0,0,5],
              [3,-4,2],
              [1,6,5],
              [0, 1,0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [10]:
U, s, W = np.linalg.svd(A)
V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [29]:
# проверим
U.dot(D).dot(V.T)

array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1., -0.]])

In [31]:
print(f'U: \n{U}\n\nD:\n{D}\n\nV: \n{V}')

U: 
[[ 0.170565   0.1568092 -0.5307751 -0.7990537 -0.161584 ]
 [ 0.3928702 -0.5293395  0.6134793 -0.4337577  0.0308249]
 [-0.1436615 -0.8244926 -0.523791   0.1404985  0.0740034]
 [ 0.888437   0.0607435 -0.2465528  0.3775583 -0.0604263]
 [ 0.0812505  0.1083184 -0.0823142 -0.1052485  0.9817396]]

D:
[[8.8248689 0.        0.       ]
 [0.        6.1406061 0.       ]
 [0.        0.        2.5327153]
 [0.        0.        0.       ]
 [0.        0.        0.       ]]

V: 
[[ 0.0711645 -0.3673782 -0.9273451]
 [ 0.7170247  0.6651408 -0.2084786]
 [ 0.6934055 -0.650093   0.3107537]]



2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.
    

### Решение

__а)__

$$\left \| A \right \|_{E}=\text{max}\left (\frac{\left \| Ax \right \|}{\left \| x \right \|}\right ) =\mu_{1}$$

In [33]:
print(f'Евклидова норма матрица А = {s[0]}')

Евклидова норма матрица А = 8.824868854820444


__б)__

Норма Фробениуса:
$$\left \| A \right \|_{F}=\sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n}a_{ij}^{2}}.$$

или


$$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}.$$

In [19]:
# Расчет нормы Фробениуса через элементы матрицы А: 
q = 0
n,k = A.shape
for i in range(n):
  for j in range(k):
    q += A[i,j]**2
q**(1/2)


11.045361017187261

In [34]:
# можно просто посчитать норму А
np.linalg.norm(A)

11.045361017187261

In [37]:
# Расчет нормы Фробениуса если известно SVD:
q = 0
for i in s:
  q += i**2
q**(1/2)


11.045361017187263

In [36]:
# или просто
np.linalg.norm(s)

11.045361017187263